name: dp-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - duckdb=0.9.2
  - pandas=2.0.3
  - numpy=1.24.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scipy=1.11.1
  - jupyter=1.0.0
  - pytest=7.4.0
  - pip
  - pip:
    - scikit-learn==1.3.0